In [1]:
!pip install tensorflow==2.15.0

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 239.1/239.1 MB 4.7 MB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 4.9 MB/s eta 0:00:00ta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 8.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 4.5 MB/s eta 0:00:00a 0:00:01m
  Attempting uninstall: ml-dtypes0m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/10 [oauthlib]
    Found existing installation: ml-dtypes 0.3.2━━━━━━━━━━━━━━  2/10 [oauthlib]
    Uninstalling ml-dtypes-0.3.2:━━━━━━━━━━━━━━━━━━━━━━━━━━━━━  2/10 [oauthlib]
      Successfully uninstalled ml-dtypes-0.3.2━━━━━━━━━━━━━━━━  2/10 [oauthlib]
  Attempting uninstall: keras╺━━━━━━━━━━━━━━━━━━━━━━━━━━━  3/10 [ml-dtypes]
    Found existing installation: keras 3.7.0━━━━━━━━━━━━━━━━━━━━━━  4/10 [keras]
    Uninstalling keras-3.7.0:╺━━━━━━━━━━━━━━━━━━━━━━━  4/10 [keras]
      Successfully uninstalled keras-3.7.0━━━━━━━━━━━━━━━━━━━━  4/10 [keras]
  Attempting uninstall: tensorboardm

In [4]:
!pip install -r requirements.txt

  Using cached pypdf-5.6.0-py3-none-any.whl.metadata (7.2 kB)
  Using cached bs4-0.0.2-py2.py3-none-any.whl.metadata (411 bytes)
  Using cached arxiv-2.2.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached pymupdf-1.26.1-cp39-abi3-macosx_10_9_x86_64.whl.metadata (3.4 kB)
  Using cached chromadb-1.0.12-cp39-abi3-macosx_10_12_x86_64.whl.metadata (6.9 kB)
  Using cached faiss_cpu-1.11.0-cp311-cp311-macosx_14_0_x86_64.whl.metadata (4.8 kB)
  Using cached langchain_groq-0.3.2-py3-none-any.whl.metadata (2.6 kB)
  Using cached duckdb-1.3.0-cp311-cp311-macosx_12_0_x86_64.whl.metadata (7.0 kB)
  Using cached wikipedia-1.4.0.tar.gz (27 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      ERROR: Can not execute `setup.py` since setuptools failed to import in the build environment with exception:
      Traceback (most recent call last):
        File "<pip-setup

In [66]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [67]:
#load the dataset
data=pd.read_csv("Churn_Modelling.csv")
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [68]:
#drop irrelevant features - preprocess the data
data=data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [69]:
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [70]:
#encode categorical variable
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])
data

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [71]:
#onehotencode geography column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo=OneHotEncoder()
geo_encoder=onehot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoder

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [72]:
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [73]:
onehot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [74]:
#convert into sparse value
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))

In [75]:
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [76]:
#combine encolder columns with opriginal data
data=pd.concat([data.drop("Geography", axis=1),geo_encoded_df], axis=1)
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  
0                0.0              0.0  
1                0.0              1.0  
2                0.0              0.0  
3                0.0              0.0  
4                0.0              1.0

In [77]:
#Save the encoders and scalers
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)
    
with open("onehot_encoder_geo.pkl","wb") as file:
    pickle.dump(onehot_encoder_geo,file)

In [78]:
#decide the dataset into independent and dependent variable
X=data.drop("Exited", axis=1)
y=data["Exited"]

#split the data into training and testing set
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=0.2,random_state=42)

#scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [79]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [80]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler, file)

In [81]:
#ANN Implementation - sequential network-interconnected nodes
#train
#sequential
#dense = how many nodes you need in hidden layer
#activation function- sigmoid, tahn, relu, leaky relu
#optimizer - useful in backl propagation-useful in updating weights
#loss function- reduce loss -gradient descent
#metrics - accuracy, mse, mae
#training-logs, folder - tensorboard -visualization

In [82]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [83]:
#Xtrain.shape - no.of columns = input nodes

In [84]:
#build our Ann model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), #hl1 connected with input layer
    Dense(32,activation="relu"), # hl2
    Dense(1,activation="sigmoid") # output layer
    
])

In [85]:
#parameters - combinational of weights and bias
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                832       
                                                                 
 dense_4 (Dense)             (None, 32)                2080      
                                                                 
 dense_5 (Dense)             (None, 1)                 33        
                                                                 
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [86]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [87]:
#compile the model
model.compile(optimizer=opt,loss="binary_crossentropy",metrics=["accuracy"])

In [88]:
#set up the Tensorboard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard

log_dir="logs/fit" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=tensorflow_callback=TensorBoard(log_dir=log_dir)

In [89]:
#set up Early Stopping - can train for any number of epochs 
# if nly 20 epochs at batch levels and it's not changing any more no need for 100 epochs
# if loss value is no longer decreasing - no need to run the training

early_stopping_callback=EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

In [90]:
# Train the model
history=model.fit(X_train, y_train,validation_data=(X_test,y_test),epochs=100,callbacks=[tensorflow_callback,early_stopping_callback])

Epoch 1/100
250/250 [==============================] - 2s 4ms/step - loss: 0.3950 - accuracy: 0.8378 - val_loss: 0.3541 - val_accuracy: 0.8510
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3544 - accuracy: 0.8519 - val_loss: 0.3440 - val_accuracy: 0.8605
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3480 - accuracy: 0.8569 - val_loss: 0.3531 - val_accuracy: 0.8595
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3448 - accuracy: 0.8579 - val_loss: 0.3456 - val_accuracy: 0.8550
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3411 - accuracy: 0.8619 - val_loss: 0.3503 - val_accuracy: 0.8595
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3405 - accuracy: 0.8605 - val_loss: 0.3675 - val_accuracy: 0.8590
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3364 - accuracy: 0.8630 - val_loss: 0.3486 - val_accuracy: 0.8605

In [107]:
model.save('model.keras')

In [108]:
#load TensorBoard extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [109]:
%tensorboard --logdir logs/fit20250613-213245

Reusing TensorBoard on port 6007 (pid 1516), started 10:07:53 ago. (Use '!kill 1516' to kill it.)

In [110]:
from tensorflow.keras.models import load_model

# load the tarined model, scaler pickle, onehot
model=load_model('model.h5')

#load the encoder and scaler
with open('onehot_encoder_geo.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    label_encoder_geo=pickle.load(file)
    
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)


In [111]:
#example input data
input_data={
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [112]:
# one hot encode 'Geography'
geo_encoded=onehot_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

/opt/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [113]:
input_df=pd.DataFrame([input_data])
input_df

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [114]:
#encode categorical variables
input_df["Gender"]=label_encoder_gender.transform(input_df["Gender"])


In [115]:
#concat one hot encoded
input_df=pd.concat([input_df.drop("Geography", axis=1),geo_encoded_df], axis=1)
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [116]:
#scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [117]:
#Predict churn
prediction=model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 163ms/step


array([[0.05450823]], dtype=float32)

In [118]:
#prediction probability
prediction_proba=prediction[0][0]
prediction_proba

0.054508228

In [119]:
if prediction_proba > 0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is not likely to churn.")

The customer is not likely to churn.
